### ISSUE TITLE
Other error

### ISSUE THREAD

**Issue by alvaromaltrain** [sam1322/rpc-extension#8]
I got another error; I already have the app created with its client ID, but I'm still getting an error

C:\Users\anonimo\Desktop\rpc-extension-main\nodejs>npm run start

> rpc-server@1.0.0 start
> node index.js

Server running on port 3003
Error: Could not connect
    at Socket.onerror (C:\Users\anonimo\Desktop\rpc-extension-main\nodejs\node_modules\discord-rpc\src\transports\ipc.js:32:16)
    at Object.onceWrapper (node:events:634:26)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Received POST request: {
  smallImageKey: 'https://res.cloudinary.com/dw5xqmxyu/image/upload/v1721882387/play4_kppcqd.png',
  smallImageText: 'Playing',
  buttons: [
    {
      label: 'Watch Along',
      url: 'https://www.youtube.com/watch?v=hDoISXuNyD8'
    },
    {
      label: 'Follow Channel',
      url: 'https://www.youtube.com/channel/UC_qa6pm1q2D--ivbxeuFMMw'
    }
  ],
  endTimestamp: 1722893943,
  startTimestamp: 1722893786,
  details: "Sube Pa'l Vip",
  state: 'Plan B - Topic',
  largeImageKey: 'https://i.ytimg.com/vi/hDoISXuNyD8/hqdefault.jpg',
  largeImageText: "Sube Pa'l Vip"
}
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read properties of null (reading 'write')
      at IPCTransport.send (C:\Users\anonimo\Desktop\rpc-extension-main\nodejs\node_modules\discord-rpc\src\transports\ipc.js:155:17)
      at C:\Users\anonimo\Desktop\rpc-extension-main\nodejs\node_modules\discord-rpc\src\client.js:159:22
      at new Promise (<anonymous>)
      at RPCClient.request (C:\Users\anonimo\Desktop\rpc-extension-main\nodejs\node_modules\discord-rpc\src\client.js:157:12)
      at RPCClient.setActivity (C:\Users\anonimo\Desktop\rpc-extension-main\nodejs\node_modules\discord-rpc\src\client.js:518:17)
      at updatePresence (C:\Users\anonimo\Desktop\rpc-extension-main\nodejs\DiscordActivity\update-discord.js:5:9)
      at updateDiscordActivity (C:\Users\anonimo\Desktop\rpc-extension-main\nodejs\DiscordActivity\update-discord.js:77:5)
      at C:\Users\anonimo\Desktop\rpc-extension-main\nodejs\index.js:53:35
      at Layer.handle [as handle_request] (C:\Users\anonimo\Desktop\rpc-extension-main\nodejs\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\anonimo\Desktop\rpc-extension-main\nodejs\node_modules\express\lib\router\route.js:149:13)
} reason: TypeError: Cannot read properties of null (reading 'write')
    at IPCTransport.send (C:\Users\anonimo\Desktop\rpc-extension-main\nodejs\node_modules\discord-rpc\src\transports\ipc.js:155:17)
    at C:\Users\anonimo\Desktop\rpc-extension-main\nodejs\node_modules\discord-rpc\src\client.js:159:22
    at new Promise (<anonymous>)
    at RPCClient.request (C:\Users\anonimo\Desktop\rpc-extension-main\nodejs\node_modules\discord-rpc\src\client.js:157:12)
    at RPCClient.setActivity (C:\Users\anonimo\Desktop\rpc-extension-main\nodejs\node_modules\discord-rpc\src\client.js:518:17)
    at updatePresence (C:\Users\anonimo\Desktop\rpc-extension-main\nodejs\DiscordActivity\update-discord.js:5:9)
    at updateDiscordActivity (C:\Users\anonimo\Desktop\rpc-extension-main\nodejs\DiscordActivity\update-discord.js:77:5)
    at C:\Users\anonimo\Desktop\rpc-extension-main\nodejs\index.js:53:35
    at Layer.handle [as handle_request] (C:\Users\anonimo\Desktop\rpc-extension-main\nodejs\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\anonimo\Desktop\rpc-extension-main\nodejs\node_modules\express\lib\router\route.js:149:13)
Clearing Rich Presence and shutting down...
Error during shutdown: TypeError: Cannot read properties of null (reading 'write')
    at IPCTransport.send (C:\Users\anonimo\Desktop\rpc-extension-main\nodejs\node_modules\discord-rpc\src\transports\ipc.js:155:17)
    at C:\Users\anonimo\Desktop\rpc-extension-main\nodejs\node_modules\discord-rpc\src\client.js:159:22
    at new Promise (<anonymous>)
    at RPCClient.request (C:\Users\anonimo\Desktop\rpc-extension-main\nodejs\node_modules\discord-rpc\src\client.js:157:12)
    at RPCClient.clearActivity (C:\Users\anonimo\Desktop\rpc-extension-main\nodejs\node_modules\discord-rpc\src\client.js:540:17)
    at handleExit (C:\Users\anonimo\Desktop\rpc-extension-main\nodejs\DiscordActivity\clearStatus.js:6:19)
    at process.<anonymous> (C:\Users\anonimo\Desktop\rpc-extension-main\nodejs\index.js:140:3)
    at process.emit (node:events:519:28)
    at emitUnhandledRejection (node:internal/process/promises:250:13)
    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)

**Comment by sam1322** [comment]
it is possible that you haven't opened discord opened yet 
The problem is that for node js script to work discord must be opened at all times so that the nodejs script can connect to the rpc server in discord client.
if this is not the case then try searching this problem on chatgpt or claude.ai

**Comment by alvaromaltrain** [comment]
Here I recorded a video of what I do; I don't know if I missed anything

https://github.com/user-attachments/assets/fb0e4ef1-fbe0-4b86-b6ab-2fca275ea7b9

**Comment by sri-vasitum** [comment]
one thing you can try is by printing the application id with  the help of console if it is undefined the convert that .env.local into .env

**Comment by alvaromaltrain** [comment]
Solution const clientId = "client id";
